### ISSUE TITLE
Link in README.md is broken

### ISSUE THREAD

**Issue by leonwind** [walnutwaldo/D-DALLE#6]
The link to [ddalle.xyz](https://ddalle.xyz) in the README is broken and links to [https://github.com/walnutwaldo/D-DALLE/blob/main/ddalle.xyz](https://github.com/walnutwaldo/D-DALLE/blob/main/ddalle.xyz).

cc @florianjuengermann for the urgent bug fix!

**Comment by walnutwaldo** [comment]
Thank you for the heads up!
